import fs from "fs";
import type { Asset } from "@/lib/assets";
import { getAssetSourceFileName } from "@/lib/assets";
import type { DeckLang } from "@/lib/html-deck-i18n";
import {
  defaultExportFormat,
  exportFileName,
  type ExportFormat,
  isHtmlExportable,
} from "./formats";
import {
  assetNeedsExport,
  editableOutputPath,
  findCachedExport,
  htmlSourcePath,
} from "./generate";

export interface ResolvedDownload {
  fileUrl: string;
  fileName: string;
  /** When true, client should POST to fileUrl to receive generated bytes */
  requiresGeneration: boolean;
}

export function resolveDownloadForAsset(
  asset: Asset,
  options: {
    deckLang?: DeckLang;
    exportFormat?: ExportFormat;
    root?: string;
  } = {}
): ResolvedDownload {
  const root = options.root ?? process.cwd();
  const fileName = getAssetSourceFileName(asset);
  const format =
    options.exportFormat ?? defaultExportFormat(asset.contentType, fileName);

  if (!isHtmlExportable(fileName)) {
    return {
      fileUrl: asset.fileUrl,
      fileName,
      requiresGeneration: false,
    };
  }

  const deckLang = options.deckLang ?? "en";

  if (!assetNeedsExport(asset, deckLang, format)) {
    return {
      fileUrl: asset.fileUrl,
      fileName: exportFileName(asset.title, deckLang, format),
      requiresGeneration: false,
    };
  }

  const cached = findCachedExport(asset, deckLang, format, root);
  if (cached) {
    return {
      fileUrl: cached.fileUrl,
      fileName: cached.fileName,
      requiresGeneration: false,
    };
  }

  // Fallback: pre-generated file on disk without manifest row (or stale manifest).
  const { absPath, fileName: editableName, fileUrl: editableUrl } =
    editableOutputPath(asset, deckLang, format, root);
  if (fs.existsSync(absPath)) {
    return {
      fileUrl: editableUrl,
      fileName: editableName,
      requiresGeneration: false,
    };
  }

  const params = new URLSearchParams({
    assetId: asset.id,
    deckLang,
    format,
  });

  return {
    fileUrl: `/api/export?${params.toString()}`,
    fileName: exportFileName(asset.title, deckLang, format),
    requiresGeneration: true,
  };
}

export function htmlSourceExists(asset: Asset, root = process.cwd()): boolean {
  return fs.existsSync(htmlSourcePath(asset, root));
}
