import type { Asset } from "@/lib/assets";
import { getAssetSourceFileName } from "@/lib/assets";
import type { DeckLang } from "@/lib/html-deck-i18n";
import {
  defaultExportFormat,
  exportFileName,
  type ExportFormat,
  isHtmlExportable,
} from "./formats";
import {
  assetNeedsExport,
  editableOutputPath,
  findManifestEntry,
} from "./cache";

export interface ResolvedDownload {
  fileUrl: string;
  fileName: string;
  /** When true, client should fetch fileUrl to receive generated bytes */
  requiresGeneration: boolean;
}

export function buildDownloadApiUrl(
  assetId: string,
  deckLang: DeckLang,
  format: ExportFormat
): string {
  const params = new URLSearchParams({
    assetId,
    deckLang,
    format,
  });
  return `/api/download?${params.toString()}`;
}

export function resolveDownloadForAsset(
  asset: Asset,
  options: {
    deckLang?: DeckLang;
    exportFormat?: ExportFormat;
    root?: string;
  } = {}
): ResolvedDownload {
  const root = options.root ?? process.cwd();
  const fileName = getAssetSourceFileName(asset);
  const format =
    options.exportFormat ?? defaultExportFormat(asset.contentType, fileName);

  if (!isHtmlExportable(fileName)) {
    return {
      fileUrl: asset.fileUrl,
      fileName,
      requiresGeneration: false,
    };
  }

  const deckLang = options.deckLang ?? "en";

  if (!assetNeedsExport(asset, deckLang, format)) {
    return {
      fileUrl: asset.fileUrl,
      fileName: exportFileName(asset.title, deckLang, format),
      requiresGeneration: false,
    };
  }

  const manifestEntry = findManifestEntry(asset.id, deckLang, format, root);
  const { fileName: editableName } = editableOutputPath(
    asset,
    deckLang,
    format,
    root
  );

  return {
    fileUrl: buildDownloadApiUrl(asset.id, deckLang, format),
    fileName: manifestEntry?.fileName ?? editableName,
    requiresGeneration: true,
  };
}
