import productPageCopy from "./product-page.copy.json";

export type ProductPageCopyEntry = {
  label?: string;
  description?: string;
};

type CopyRoot = Record<string, Record<string, ProductPageCopyEntry>>;

const data = productPageCopy as CopyRoot;

/**
 * Localized intro/title for `/assets/product/[slug]` from `lib/product-page.copy.json`
 * (generated by `npm run assets:from-inventory` from workbook “product page” sheets).
 */
export function getProductPageCopy(
  locale: string,
  productSlug: string
): ProductPageCopyEntry | null {
  const loc = data[locale] ?? data.en;
  if (!loc) return null;
  const entry = loc[productSlug];
  if (!entry) return null;
  if (!entry.description?.trim() && !entry.label?.trim()) return null;
  return entry;
}
